apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golem

resources:
  - ../../base

bases:
  - ../../base

patches:
  # Update Ingress host for production
  - target:
      kind: Ingress
      name: golem-century
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prod.game.anhtran.dev
      - op: replace
        path: /spec/tls/0/hosts/0
        value: prod.game.anhtran.dev

commonLabels:
  environment: production
