apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

commonLabels:
  environment: production

patches:
  - patch: |-
      - op: replace
        path: /data/REDIS_ADDR
        value: "redis.default.svc.cluster.local:6379"
    target:
      kind: ConfigMap
      name: golem-app-config
