FROM golang:1.25.0-alpine AS builder

WORKDIR /app

# Copy dependency files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY cmd/transport/ ./cmd/transport/

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o transport ./cmd/transport

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/transport .

EXPOSE 8000
CMD ["./transport"]
