apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-game
  labels:
    app: game
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: FIRESTORE_PROJECT_ID
              value: {{ .Values.env.FIRESTORE_PROJECT_ID | quote }}
            - name: REDIS_ADDR
              value: {{ .Values.env.REDIS_ADDR | quote }}
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: TELEGRAM_CHAT_ID
            - name: FIRESTORE_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: FIRESTORE_CREDENTIALS
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: S3_ENDPOINT
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: S3_REGION
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: S3_SECRET_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: S3_BUCKET
