apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: {{ default "" .Values.secrets.TELEGRAM_BOT_TOKEN | b64enc | quote }}
  TELEGRAM_CHAT_ID: {{ default "" .Values.secrets.TELEGRAM_CHAT_ID | b64enc | quote }}
  FIRESTORE_CREDENTIALS: {{ default "" .Values.secrets.FIRESTORE_CREDENTIALS | b64enc | quote }}
  S3_ENDPOINT: {{ default "" .Values.secrets.S3_ENDPOINT | b64enc | quote }}
  S3_REGION: {{ default "" .Values.secrets.S3_REGION | b64enc | quote }}
  S3_ACCESS_KEY: {{ default "" .Values.secrets.S3_ACCESS_KEY | b64enc | quote }}
  S3_SECRET_KEY: {{ default "" .Values.secrets.S3_SECRET_KEY | b64enc | quote }}
  S3_BUCKET: {{ default "" .Values.secrets.S3_BUCKET | b64enc | quote }}
