apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golem-frontend-pvc
  labels:
    app: golem
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
