apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: golem-gateway-reference
  namespace: nginx-gateway
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: default
  to:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: main-gateway
